{% set version = "0.14" %}

package:
  name: docstring-to-markdown
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/docstring-to-markdown/docstring-to-markdown-{{ version }}.tar.gz
  sha256: f9b061b42ee848149e122a647013b4f0778141596230f3203fe7f5404b3e9ab2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  source_files:
    - tests
  imports:
    - docstring_to_markdown
  commands:
    - pip check
    - pytest -vv --cov=docstring_to_markdown --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=97
  requires:
    - pip
    - pytest-cov

about:
  home: https://pypi.org/project/docstring-to-markdown
  summary: On the fly conversion of Python docstrings to markdown
  license: LGPL-2.1-or-later
  license_file: LICENSE
  dev_url: https://github.com/python-lsp/docstring-to-markdown

extra:
  recipe-maintainers:
    - bollwyvl
