{% set version = "0.12" %}

package:
  name: docstring-to-markdown
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/docstring-to-markdown/docstring-to-markdown-{{ version }}.tar.gz
  sha256: 40004224b412bd6f64c0f3b85bb357a41341afd66c4b4896709efa56827fb2bb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - docstring_to_markdown
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/docstring-to-markdown
  summary: On the fly conversion of Python docstrings to markdown
  license: LGPL-2.1-or-later
  license_file: LICENSE
  dev_url: https://github.com/python-lsp/docstring-to-markdown

extra:
  recipe-maintainers:
    - bollwyvl
