{% set version = "0.16" %}

package:
  name: docstring-to-markdown
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/docstring-to-markdown/docstring_to_markdown-{{ version }}.tar.gz
  sha256: 097bf502fdf040b0d019688a7cc1abb89b98196801448721740e8aa3e5075627

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - docstring_to_markdown
  commands:
    - pip check
    - pytest -vv --cov=docstring_to_markdown --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=97
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}

about:
  home: https://pypi.org/project/docstring-to-markdown
  summary: On the fly conversion of Python docstrings to markdown
  license: LGPL-2.1-or-later
  license_file: LICENSE
  dev_url: https://github.com/python-lsp/docstring-to-markdown

extra:
  recipe-maintainers:
    - bollwyvl
