# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.16

package:
  name: docstring-to-markdown
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/docstring-to-markdown/docstring_to_markdown-${{ version }}.tar.gz
  sha256: 097bf502fdf040b0d019688a7cc1abb89b98196801448721740e8aa3e5075627

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - importlib-metadata >=3.6
    - typing_extensions >=4.6

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
      imports: docstring_to_markdown
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - coverage run --source=docstring_to_markdown --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=99

about:
  summary: On the fly conversion of Python docstrings to markdown
  license: LGPL-2.1-or-later
  license_file: LICENSE
  homepage: https://pypi.org/project/docstring-to-markdown
  repository: https://github.com/python-lsp/docstring-to-markdown

extra:
  recipe-maintainers:
    - bollwyvl
